[package]
name = "kataan-search"
version = "2.0.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
blake3.workspace = true
kataan-core = { path = "../kataan-core" }
rusqlite.workspace = true
serde.workspace = true

[dev-dependencies]
tempfile.workspace = true
